apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vendor-ingress-staging
  namespace: vendor-staging
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:286757679229:certificate/5202447b-7f76-4419-a0bc-edf100107520
    alb.ingress.kubernetes.io/ssl-redirect: "443"
spec:
  rules:
    - host: vendorstaging.caasdiglobal.in
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: vendor-backend-staging
                port:
                  number: 5001
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vendor-frontend-staging
                port:
                  number: 80


